server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Public routes (no auth required)
        - id: user-service-public
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/register
          filters:
            - StripPrefix=0

        # Protected routes (auth required)
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - TokenRelay

        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/products/**
          filters:
            - TokenRelay

        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - TokenRelay

        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - TokenRelay

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: BVhUORbVaWuCM9tVA7ZE1ByaCWBz1BpH
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
        provider:
          keycloak:
            authorization-uri: http://localhost:8090/realms/ecommerce/protocol/openid-connect/auth
            token-uri: http://localhost:8090/realms/ecommerce/protocol/openid-connect/token
            user-info-uri: http://localhost:8090/realms/ecommerce/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8090/realms/ecommerce/protocol/openid-connect/certs
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/realms/ecommerce/protocol/openid-connect/certs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
