server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Ruta para reenviar al monolito
        - id: monolith-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/**
        # Ruta para servicio de inventario
        - id: inventory-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/inventory/**

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
